public enum TipoHabilidadEspecialTrampa {
    FUERZA_DE_ESPEJO, CILINDRO_MAGICO, TRIBUTO_TORRENCIAL, ARMADURA_DE_SAKURETSU, LLAMADA_DE_LOS_CONDENADOS, SOMBREROS_MAGICOS, WABOKU, MURO_DE_ESPEJO, REPRESION, DRENAJE_DE_HABILIDAD, INVOCACION, BATALLA
}
