public enum TipoHabilidadEspecial {
    MONSTRUO_RENACIDO, AGUJERO_NEGRO, TIFON_DEL_ESPACIO_MISTICO, ESPADAS_DE_LA_LUZ_REVELADORA, OLLA_DE_LA_CODICIA, ENTIERRO_INSENSATO, RAIGEKI, MIL_CUCHILLOS, UNIDAD, POLIMERIZACION
}
